<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I Agree to the_signin</name>
   <tag></tag>
   <elementGuidId>e58e571a-0fe9-4f0b-a449-31d307dda53d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sign In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cff18043-4ca2-4c6a-af89-27fbbc3a03cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInBtn</value>
      <webElementGuid>04df2cd2-57e3-4bc4-b36b-9f68658eaa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>701bb4fb-c70a-4815-b42a-8cd0d5d7f5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signin</value>
      <webElementGuid>4367019e-2ae4-4bf8-9a17-3da6a6bd493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-md</value>
      <webElementGuid>d9289f74-91d3-46f3-aebe-f27d7963dcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>638a91ee-b4cd-417f-b743-2b55d43a64de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInBtn&quot;)</value>
      <webElementGuid>bf30d990-816d-430a-9692-71ddcaabd093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInBtn']</value>
      <webElementGuid>776aab88-a7d5-44f3-95ce-44e3abdae7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/input</value>
      <webElementGuid>3c96b96f-42d3-407a-8693-becc9b3bb637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>c7c8afd4-154f-4dd7-937c-79979217f18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInBtn' and @type = 'submit' and @name = 'signin']</value>
      <webElementGuid>b9d26d43-0504-469e-a088-75acae5aeb95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
