<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File Upload_upload-btn</name>
   <tag></tag>
   <elementGuidId>3703a4cd-953f-45da-826e-df39b82ee95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='upload-btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;upload-btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;upload-btn&quot;]</value>
      <webElementGuid>8fd6d545-f181-46e9-b3db-0ea427551b3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='upload-btn']</value>
      <webElementGuid>cef5d118-bd81-40ad-85f2-07f06d55c713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f13587-p1037-o1']/form/p/input</value>
      <webElementGuid>190b6ca9-2185-4358-beaf-79b0f9fcccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>a7c3b957-7d74-4ef2-a29b-2eb2da05db7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'upload-btn' and @type = 'submit']</value>
      <webElementGuid>ea596d46-c57d-4b7e-9a9c-28b77969840e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
